import type { AdminContent } from '@/types/admin';

const listingCards = [
  {
    id: 1,
    imageSrc: '/img/dashboard/listing/1.jpg',
    location: 'Boracay, Philippines',
    title: 'Boracay Island Hopping and White Beach Escape',
    rating: 4.8,
    ratingCount: 243,
    duration: '4 Days',
    price: 10888,
    fromPrice: 11990,
  },
  {
    id: 2,
    imageSrc: '/img/dashboard/listing/2.jpg',
    location: 'Palawan, Philippines',
    title: 'El Nido Lagoons and Island Adventure Tour',
    rating: 4.7,
    ratingCount: 188,
    duration: '4 Days',
    price: 14500,
    fromPrice: 15900,
  },
  {
    id: 3,
    imageSrc: '/img/dashboard/listing/3.jpg',
    location: 'Bangkok, Thailand',
    title: 'Bangkok Highlights with Market and Temple Stops',
    rating: 4.8,
    ratingCount: 206,
    duration: '3 Days',
    price: 15888,
    fromPrice: 16950,
  },
  {
    id: 4,
    imageSrc: '/img/dashboard/listing/4.jpg',
    location: 'Singapore',
    title: 'Singapore Skyline and Sentosa City Experience',
    rating: 4.9,
    ratingCount: 174,
    duration: '3 Days',
    price: 18250,
    fromPrice: 19750,
  },
  {
    id: 5,
    imageSrc: '/img/dashboard/listing/5.jpg',
    location: 'Bohol, Philippines',
    title: 'Countryside Tour with River Cruise and Tarsier Stop',
    rating: 4.8,
    ratingCount: 132,
    duration: '2 Days',
    price: 9250,
    fromPrice: 10200,
  },
  {
    id: 6,
    imageSrc: '/img/dashboard/listing/6.jpg',
    location: 'Cebu, Philippines',
    title: 'Cebu Heritage and Southern Coast Getaway Package',
    rating: 4.7,
    ratingCount: 158,
    duration: '3 Days',
    price: 12890,
    fromPrice: 13990,
  },
] as const;

export const adminContent: AdminContent = {
  metadata: {
    main: {
      title: 'Admin | Travel & Tours',
      description: 'Manage bookings, listings, messages, and profile settings.',
    },
    destinations: {
      title: 'Destinations | Travel & Tours',
      description: 'Manage destination records and visibility.',
    },
    booking: {
      title: 'My Booking | Travel & Tours',
      description: 'Review approved, pending, and cancelled bookings.',
    },
    listing: {
      title: 'My Listings | Travel & Tours',
      description: 'View and manage your listed travel packages.',
    },
    addTour: {
      title: 'Add Tour | Travel & Tours',
      description: 'Create a new tour listing for your dashboard.',
    },
    favorites: {
      title: 'My Favorites | Travel & Tours',
      description: 'Access your favorite travel package list.',
    },
    messages: {
      title: 'Messages | Travel & Tours',
      description: 'Read and reply to your inbox messages.',
    },
    profile: {
      title: 'My Profile | Travel & Tours',
      description: 'Update your profile details and password.',
    },
  },
  shell: {
    brandLabel: 'Travel & Tours',
    searchPlaceholder: 'Search',
    footerPrefix: 'Copyright Travel & Tours',
    navItems: [
      { id: 1, href: '/admin/dashboard', iconClass: 'icon-dashboard text-26', label: 'Dashboard' },
      { id: 2, href: '/admin/destinations', iconClass: 'icon-pin text-26', label: 'Destinations' },
      { id: 3, href: '/admin/booking', iconClass: 'icon-calendar text-26', label: 'Bookings' },
      { id: 4, href: '/admin/listing', iconClass: 'icon-menu text-26', label: 'My Listings' },
      { id: 5, href: '/admin/add-tour', iconClass: 'icon-clipboard text-26', label: 'Add Tour' },
      { id: 6, href: '/admin/favorites', iconClass: 'icon-heart text-26', label: 'My Favorites' },
      { id: 7, href: '/admin/messages', iconClass: 'icon-message text-26', label: 'Messages' },
      { id: 8, href: '/admin/profile', iconClass: 'icon-account text-26', label: 'My Profile' },
      { id: 9, href: '/logout', iconClass: 'icon-logout text-26', label: 'Logout' },
    ],
    topActions: [
      { id: 1, iconClass: 'icon-mail text-20', label: 'Notifications' },
      { id: 2, iconClass: 'icon-bell text-20', label: 'Alerts' },
      { id: 3, imageSrc: '/img/dashboard/header/1.png', label: 'Profile avatar' },
    ],
  },
  pages: {
    main: {
      intro: {
        title: 'Admin',
        description: 'Track your latest activity, performance, and booking updates.',
      },
      todayLabel: 'Today',
      activitiesTitle: 'Recent Activities',
      activitiesCtaLabel: 'View More',
      chartTitle: 'Earning Statistics',
      statCards: [
        {
          id: 1,
          title: 'Total Earnings',
          amount: '$10,800',
          today: '$50',
          iconClass: 'icon-wallet text-accent-1',
        },
        {
          id: 2,
          title: 'Total Pending',
          amount: '$12,800',
          today: '40+',
          iconClass: 'icon-payment text-accent-1',
        },
        {
          id: 3,
          title: 'Total Booking',
          amount: '$54,800',
          today: '90+',
          iconClass: 'icon-booking text-accent-1',
        },
        {
          id: 4,
          title: 'Wishlist',
          amount: '1834',
          today: '290+',
          iconClass: 'icon-heart text-accent-1',
        },
      ],
      activities: [
        {
          id: 1,
          iconClass: 'icon-home',
          message: 'Your listing House on the Beverly Hills has been approved',
        },
        {
          id: 2,
          iconClass: 'icon-review',
          message: 'Dollie Horton left a review on House on the Northridge',
        },
        {
          id: 3,
          iconClass: 'icon-heart',
          message: 'Someone favorited your Triple Story House for Rent listing',
        },
        {
          id: 4,
          iconClass: 'icon-home',
          message: 'Your listing House on the Beverly Hills has been approved',
        },
      ],
      chartTabs: [
        {
          id: 1,
          label: 'Hours',
          data: [
            { name: '12PM', value: 148 },
            { name: '2AM', value: 100 },
            { name: '4AM', value: 205 },
            { name: '6AM', value: 110 },
            { name: '8AM', value: 165 },
            { name: '10AM', value: 145 },
            { name: '12AM', value: 180 },
            { name: '2PM', value: 156 },
            { name: '4PM', value: 148 },
            { name: '6PM', value: 220 },
            { name: '8PM', value: 180 },
            { name: '10PM', value: 245 },
          ],
        },
        {
          id: 2,
          label: 'Weekly',
          data: [
            { name: '1st', value: 158 },
            { name: '2nd', value: 210 },
            { name: '3rd', value: 180 },
            { name: '4th', value: 235 },
            { name: '5th', value: 100 },
          ],
        },
        {
          id: 3,
          label: 'Monthly',
          data: [
            { name: 'Jan', value: 158 },
            { name: 'Feb', value: 100 },
            { name: 'Mar', value: 235 },
            { name: 'Apr', value: 210 },
            { name: 'May', value: 165 },
            { name: 'Jun', value: 145 },
            { name: 'Jul', value: 190 },
            { name: 'Aug', value: 156 },
            { name: 'Sep', value: 148 },
            { name: 'Oct', value: 210 },
            { name: 'Nov', value: 180 },
            { name: 'Dec', value: 235 },
          ],
        },
      ],
    },
    destinations: {
      intro: {
        title: 'Destinations',
        description: 'Manage destination setup from your dashboard.',
      },
      addButtonLabel: 'Add Destination',
      addModal: {
        title: 'Add Destination',
        fields: {
          name: 'Name',
          active: 'Active',
        },
        image: {
          uploadLabel: 'Upload Image',
          clearLabel: 'Remove image',
          previewAlt: 'Destination image preview',
        },
        actions: {
          cancel: 'Cancel',
          save: 'Save',
          saving: 'Saving...',
        },
        messages: {
          requiredName: 'Name is required.',
          uploadFailedPrefix: 'Image upload failed',
          createFailedPrefix: 'Failed to create destination',
          createSuccess: 'Destination created successfully.',
        },
      },
      editModal: {
        title: 'Edit Destination',
        fields: {
          name: 'Name',
          active: 'Active',
        },
        image: {
          uploadLabel: 'Upload Image',
          clearLabel: 'Remove image',
          previewAlt: 'Destination image preview',
        },
        actions: {
          cancel: 'Cancel',
          save: 'Save Changes',
          saving: 'Saving...',
        },
        messages: {
          requiredName: 'Name is required.',
          uploadFailedPrefix: 'Image upload failed',
          updateFailedPrefix: 'Failed to update destination',
          updateSuccess: 'Destination updated successfully.',
        },
      },
      table: {
        columns: {
          name: 'Name',
          image: 'Image',
          active: 'Active',
          actions: 'Actions',
        },
        statusLabels: {
          active: 'Active',
          inactive: 'Inactive',
        },
        actions: {
          editLabel: 'Edit destination',
          deleteLabel: 'Delete destination',
        },
        messages: {
          loadError: 'Failed to load destinations. Please refresh and try again.',
          empty: 'No destinations found.',
          deleteFailedPrefix: 'Failed to delete destination',
          deleteSuccess: 'Destination deleted successfully.',
        },
      },
    },
    booking: {
      intro: {
        title: 'My Booking',
        description: 'Manage your current and historical booking requests.',
      },
      tabs: ['Approved', 'Pending', 'Cancelled', 'Completed'],
    },
    listing: {
      intro: {
        title: 'My Listings',
        description: 'Review your published and draft travel package listings.',
      },
      pricePrefix: 'From',
      cards: [...listingCards],
      resultSummary: 'Showing results 1-30 of 1,415',
    },
    addTour: {
      intro: {
        title: 'Add Tour',
        description: 'Create and configure a new tour offer from your dashboard.',
      },
      tabs: [
        {
          id: 'content',
          label: 'Content',
          fields: [
            { id: 'tour-title', label: 'Tour Title', kind: 'input' },
            { id: 'category', label: 'Category', kind: 'input' },
            { id: 'keywords', label: 'Keywords', kind: 'input' },
            { id: 'tour-content', label: 'Tour Content', kind: 'textarea' },
          ],
        },
        {
          id: 'location',
          label: 'Location',
          fields: [
            { id: 'country', label: 'Country', kind: 'input' },
            { id: 'city', label: 'City', kind: 'input' },
            { id: 'address', label: 'Address', kind: 'input' },
          ],
        },
        {
          id: 'pricing',
          label: 'Pricing',
          fields: [
            { id: 'base-price', label: 'Base Price', kind: 'input' },
            { id: 'promo-price', label: 'Promo Price', kind: 'input' },
            { id: 'max-guests', label: 'Max Guests', kind: 'input' },
          ],
        },
        {
          id: 'included',
          label: 'Included',
          fields: [
            { id: 'inclusions', label: 'Inclusions', kind: 'textarea' },
            { id: 'exclusions', label: 'Exclusions', kind: 'textarea' },
          ],
        },
      ],
      galleryTitle: 'Gallery',
      uploadLabel: 'Upload Images',
      uploadHint: 'PNG or JPG no bigger than 800px wide and tall.',
      saveLabel: 'Save Changes',
      gallery: [
        { id: 'image-1', src: '', alt: 'Gallery image upload slot 1' },
        { id: 'image-2', src: '/img/dashboard/addtour/1.jpg', alt: 'Gallery image 2' },
        { id: 'image-3', src: '/img/dashboard/addtour/2.jpg', alt: 'Gallery image 3' },
        { id: 'image-4', src: '/img/dashboard/addtour/3.jpg', alt: 'Gallery image 4' },
      ],
    },
    favorites: {
      intro: {
        title: 'My Favorites',
        description: 'Quickly access saved tours you are tracking.',
      },
      cards: [...listingCards, ...listingCards.slice(0, 2).map((card) => ({ ...card, id: card.id + 100 }))],
      resultSummary: 'Showing results 1-30 of 1,415',
      pricePrefix: 'From',
    },
    messages: {
      intro: {
        title: 'Messages',
        description: 'Read and reply to traveler and team conversations.',
      },
      searchPlaceholder: 'Search',
      deleteConversationLabel: 'Delete Conversation',
      sendPlaceholder: 'Type a message',
      sendButtonLabel: 'Send Message',
      senders: [
        {
          id: 1,
          image: '/img/dashboard/messages/sidebar/1.png',
          badgeText: '2',
          name: 'Darlene Robertson',
          role: 'Head of Development',
          time: '35 mins',
        },
        {
          id: 2,
          image: '/img/dashboard/messages/sidebar/2.png',
          badgeColor: 'bg-accent-2',
          badgeText: '2',
          name: 'Arlene McCoy',
          role: 'Customer Support',
          time: '52 mins',
        },
        {
          id: 3,
          image: '/img/dashboard/messages/sidebar/3.png',
          badgeColor: 'bg-green-3',
          badgeText: '1',
          name: 'Leslie Alexander',
          role: 'Sales Associate',
          time: '1 hour',
        },
        {
          id: 4,
          image: '/img/dashboard/messages/sidebar/4.png',
          name: 'Wade Warren',
          role: 'Operations',
          time: '2 hours',
        },
      ],
      activeConversation: {
        name: 'Arlene McCoy',
        image: '/img/dashboard/messages/main/4.png',
        status: 'Active',
      },
      thread: [
        {
          id: 1,
          senderName: 'Arlene McCoy',
          senderImage: '/img/dashboard/messages/main/1.png',
          senderStatus: 'Active',
          time: '10:10 AM',
          message: 'Can you share the updated itinerary for the group tour package?',
          align: 'left',
        },
        {
          id: 2,
          senderName: 'You',
          senderImage: '/img/dashboard/header/1.png',
          time: '10:13 AM',
          message: 'Yes, I just uploaded it. Please check your email and dashboard attachments.',
          align: 'right',
        },
        {
          id: 3,
          senderName: 'Arlene McCoy',
          senderImage: '/img/dashboard/messages/main/3.png',
          time: '10:15 AM',
          message: 'Received, thank you. I will review and get back to you shortly.',
          align: 'left',
        },
      ],
    },
    profile: {
      intro: {
        title: 'My Profile',
        description: 'Manage account details, profile images, and credentials.',
      },
      profileTitle: 'Profile Details',
      profileFields: [
        { id: 'first-name', label: 'Name', kind: 'input' },
        { id: 'last-name', label: 'Last Name', kind: 'input' },
        { id: 'phone', label: 'Phone', kind: 'input' },
        { id: 'email', label: 'Email', kind: 'input' },
      ],
      profileSaveLabel: 'Save Changes',
      savingLabel: 'Saving...',
      loadingLabel: 'Loading profile...',
      photoTitle: 'Your photo',
      photoHint: 'PNG or JPG no bigger than 800px wide and tall.',
      photos: [
        { id: 'profile-photo-1', src: '', alt: 'Profile upload slot 1' },
      ],
      passwordTitle: 'Change Password',
      passwordFields: [
        { id: 'old-password', label: 'Old password', kind: 'input' },
        { id: 'new-password', label: 'New password', kind: 'input' },
        { id: 'confirm-password', label: 'Confirm new password', kind: 'input' },
      ],
      passwordSaveLabel: 'Save Changes',
      uploadLabel: 'Upload Images',
      messages: {
        fixHighlightedFields: 'Please fix the highlighted fields.',
        sessionExpired: 'Session expired. Please sign in again.',
        profileUploadFailedPrefix: 'Profile photo upload failed',
        profileTableMissing: 'Unable to save profile details. Make sure the "profiles" table exists with the required columns.',
        profileSaved: 'Profile saved successfully.',
        passwordOldIncorrect: 'Old password is incorrect.',
        passwordSaved: 'Password updated successfully.',
      },
      validationMessages: {
        required_first_name: 'First name is required.',
        required_last_name: 'Last name is required.',
        required_phone: 'Phone number is required.',
        invalid_phone: 'Please enter a valid phone number.',
        required_email: 'Email is required.',
        invalid_email: 'Please enter a valid email address.',
        required_old_password: 'Old password is required.',
        required_new_password: 'New password is required.',
        invalid_new_password_length: 'New password must be at least 8 characters.',
        invalid_new_password_pattern: 'Password must include at least one letter and one number.',
        required_confirm_password: 'Please confirm your new password.',
        mismatch_confirm_password: 'New password and confirmation do not match.',
        same_as_old_password: 'New password must be different from old password.',
      },
    },
  },
};
